# Generated by Django 5.2.16 on 2026-07-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisincidennt',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
