# Generated by Django 5.2.8 on 2026-07-25 21:03

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_crisisincidennt_is_resolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low / Resource Request'), ('MED', 'Medium / Road Blocked'), ('CRIT', 'Critical / Emergency')], default='LOW', max_length=4)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HazardZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CrisisIncidennt',
        ),
        migrations.RemoveField(
            model_name='logisticshub',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='logisticshub',
            name='longitude',
        ),
        migrations.AddField(
            model_name='logisticshub',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
